### ISSUE TITLE
Thredds cant read nopp2 for WW3 dataset

### ISSUE THREAD

**Issue by 3ximus** [CENTEC-IST/thredds-server#15]
# fc.WW3_st4.log
```
2020-09-29T18:06:07.817 +0000 INFO  - FeatureCollection added = FeatureCollectionConfig name ='WW3 st4' collectionName='WW3_st4' type='FMRC'
  spec='/usr/local/tomcat/content/thredds/public/data/WW3ST4/.*\.nc'
  dateFormatMark ='yyyyMM#.nc#$'
  olderThan =5 min
  timePartition =directory
  updateConfig =UpdateConfig{userDefined=true, recheckAfter='null', rescan='* 0 3 * * ? *', triggerOk=true, updateType=test}
  tdmConfig =UpdateConfig{userDefined=false, recheckAfter='null', rescan='null', triggerOk=true, updateType=test}
  ProtoConfig{choice=Penultimate, change='null', param='null', outerNcml='null', cacheAll=true}
  hasInnerNcml =false
  fmrcConfig =FmrcConfig: regularize=false datasetTypes=[TwoD, Best, Files, Runs]

2020-09-29T18:06:07.817 +0000 INFO  - scheduleJob startup scan force=test for 'WW3_st4' at 2020-09-29T18:06:10.817+0000
2020-09-29T18:06:07.818 +0000 INFO  - scheduleJob recurring scan for 'WW3_st4' cronExpr=* 0 3 * * ? *
2020-09-29T21:06:55.015 +0000 ERROR - UpdateCollectionJob.execute startup failed collection=WW3_st4
java.lang.NullPointerException: null
	at ucar.nc2.ft.fmrc.FmrcDataset.getNetcdfDataset2D(FmrcDataset.java:182) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.Fmrc.getDataset2D(Fmrc.java:187) ~[cdm-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:114) ~[tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.checkState(InvDatasetFeatureCollection.java:311) ~[tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.update(InvDatasetFeatureCollection.java:332) ~[tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.update(InvDatasetFcFmrc.java:88) ~[tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.sendEvent(InvDatasetFeatureCollection.java:228) ~[tdcommon-4.6.15.jar:4.6.15]
	at thredds.inventory.CollectionUpdater$UpdateCollectionJob.execute(CollectionUpdater.java:242) [cdm-4.6.15.jar:4.6.15]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]
```

# fmrc.log

```
[2020-09-29T21:06:54.703+0000] INFO  ucar.nc2.ft.fmrc.FmrcDataset: FMRCDataset build Proto cache >10M var= significant_wave_height(date=721, partition=24, latitude=361, longitude=720)
[2020-09-29T21:06:55.008+0000] ERROR ucar.nc2.ft.fmrc.Fmrc: WW3 st4: makeFmrcInv failed
java.lang.ArrayIndexOutOfBoundsException: 205856640
	at ucar.nc2.iosp.IospHelper.readData(IospHelper.java:354) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.IospHelper.readDataFill(IospHelper.java:292) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:169) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:144) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2026) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.reallyRead(Variable.java:874) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable._read(Variable.java:845) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.read(Variable.java:723) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.read(Variable.java:723) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.FmrcDataset.buildProto(FmrcDataset.java:332) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.FmrcDataset.setInventory(FmrcDataset.java:237) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.Fmrc.update(Fmrc.java:236) [cdm-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:107) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.checkState(InvDatasetFeatureCollection.java:311) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.update(InvDatasetFeatureCollection.java:332) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.update(InvDatasetFcFmrc.java:88) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.sendEvent(InvDatasetFeatureCollection.java:228) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.inventory.CollectionUpdater$UpdateCollectionJob.execute(CollectionUpdater.java:242) [cdm-4.6.15.jar:4.6.15]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar:?]
[2020-09-30T10:32:56.745+0000] INFO  ucar.nc2.ft.fmrc.FmrcDataset: FMRCDataset build Proto cache >10M var= significant_wave_height(date=721, partition=24, latitude=361, longitude=720)
[2020-09-30T10:32:57.100+0000] ERROR ucar.nc2.ft.fmrc.Fmrc: WW3 st4: makeFmrcInv failed
java.lang.ArrayIndexOutOfBoundsException: 205856640
	at ucar.nc2.iosp.IospHelper.readData(IospHelper.java:354) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.IospHelper.readDataFill(IospHelper.java:292) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:169) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.iosp.hdf5.H5iosp.readData(H5iosp.java:144) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:2026) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.reallyRead(Variable.java:874) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable._read(Variable.java:845) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.read(Variable.java:723) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.dataset.VariableDS.reallyRead(VariableDS.java:523) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.dataset.VariableDS._read(VariableDS.java:507) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.Variable.read(Variable.java:723) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.FmrcDataset.buildProto(FmrcDataset.java:332) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.FmrcDataset.setInventory(FmrcDataset.java:237) ~[cdm-4.6.15.jar:4.6.15]
	at ucar.nc2.ft.fmrc.Fmrc.update(Fmrc.java:236) [cdm-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.updateCollection(InvDatasetFcFmrc.java:107) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFeatureCollection.checkState(InvDatasetFeatureCollection.java:311) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.catalog.InvDatasetFcFmrc.makeCatalog(InvDatasetFcFmrc.java:142) [tdcommon-4.6.15.jar:4.6.15]
	at thredds.servlet.DataRootHandler.makeDynamicCatalog(DataRootHandler.java:1435) [classes/:4.6.15]
	at thredds.servlet.DataRootHandler.getCatalog(DataRootHandler.java:1403) [classes/:4.6.15]
	at thredds.server.catalogservice.LocalCatalogServiceController.handleHtmlRequest(LocalCatalogServiceController.java:253) [classes/:4.6.15]
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:849) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:760) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) [servlet-api.jar:?]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at thredds.servlet.filter.RequestQueryFilter.doFilter(RequestQueryFilter.java:118) [classes/:4.6.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364) [catalina.jar:8.5.57]
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.13.3.jar:2.13.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at thredds.servlet.filter.RequestCORSFilter.doFilterInternal(RequestCORSFilter.java:49) [classes/:4.6.15]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347) [spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263) [spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at thredds.servlet.filter.RequestPathFilter.doFilter(RequestPathFilter.java:94) [classes/:4.6.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at thredds.server.RequestBracketingLogMessageFilter.doFilter(RequestBracketingLogMessageFilter.java:81) [classes/:4.6.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.57]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [catalina.jar:8.5.57]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [catalina.jar:8.5.57]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:8.5.57]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [catalina.jar:8.5.57]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:8.5.57]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615) [tomcat-coyote.jar:8.5.57]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:8.5.57]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818) [tomcat-coyote.jar:8.5.57]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626) [tomcat-coyote.jar:8.5.57]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.57]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.57]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**Comment by 3ximus** [comment]
## NOTE
Convert time units. Instead of `hours since` convert to `seconds since` epoch

**Comment by 3ximus** [comment]
Remove Unwanted partitions, and cut coordinates to the Atlantic only.

**Comment by 3ximus** [comment]
Working on it :  a486c985aff22351cec51f23584837fbbd956056

**Comment by 3ximus** [comment]
Now the problem is lack of memory in the server to process the data
